# Generated by Django 4.2.3 on 2023-07-27 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyEmployees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeName', models.CharField(max_length=50, verbose_name='Employee Name')),
                ('companyName', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=25, null=True)),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
            ],
        ),
        migrations.CreateModel(
            name='deviceReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceName', models.CharField(max_length=50, verbose_name='Device Name')),
                ('returnDate', models.DateField(null=True, verbose_name='Return Date')),
                ('deviceCondition2', models.TextField(null=True, verbose_name='Condition of Device during handing in')),
                ('employeeName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='devicetrack.companyemployees')),
            ],
        ),
        migrations.CreateModel(
            name='deviceGive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceName', models.CharField(max_length=50, verbose_name='Device Name')),
                ('checkoutDate', models.DateField(null=True, verbose_name='Check-out Date')),
                ('deviceCondition1', models.TextField(null=True, verbose_name='Condition of Device during handing out')),
                ('employeeName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='devicetrack.companyemployees')),
            ],
        ),
    ]
