# Generated by Django 4.2.3 on 2023-07-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devicetrack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyemployees',
            name='companyName',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
