# Generated by Django 4.2.3 on 2023-07-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devicetrack', '0002_alter_companyemployees_companyname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicegive',
            name='employeeName',
            field=models.CharField(max_length=50, null=True, verbose_name='Employee Name'),
        ),
        migrations.AlterField(
            model_name='devicereturn',
            name='employeeName',
            field=models.CharField(max_length=50, null=True, verbose_name='Employee Name'),
        ),
    ]
